name = "Create Cobblemon Legends"
author = "EternalCode0"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "322f45ff1088d2f7269a0d4c91fe81ef586692377ef00def943ecb28e47e97b3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
